baseURL = "https://mikewk.com"
languageCode = "en"
title = "Michael W. Kearney"
theme = "hugo-nuo"
enableRobotsTXT = true
pygmentsuseclasses = true
PygmentsCodeFences = true
canonifyurls = true
publishDir = "docs"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$", "^make$", "^make\\.R$", "^\\.funs\\.R$"]

# Disqus Username
disqusShortname = "kearneymw"

# Google Analytics UA number
googleAnalytics = "UA-64959413-1"

# Copyright of your post
copyright = "© Michael W. Kearney 2018"

# Initial site menu, you can extend menu with content.
[[menu.main]]
  name = "Home"
  weight = 10
  identifier = "home"
  url = "/"

 [[menu.main]]
   name = "Blog"
   weight = 30
   identifier = "blog"
   url = "/post"

 [[menu.main]]
   name = "CV"
   weight = 40
   identifier = "cv"
   url = "/cv/cv.pdf"

# Add your own params here
[params]
  author = "Michael W. Kearney, Ph.D."
  avatar = "/img/aintnoseats.jpeg"
  seotitle = "Michael W. Kearney"
  subtitle1 = "Assistant Professor"
  subtitle2 = "School of Journalism"
  subtitle3 = "Informatics Institute"
  subtitle4 = "University of Missouri"
  description = "Personal website of Michael W. Kearney, assistant professor at Missouri School of Journalism and Missouri Informatics Institute"
  paginate = 10

  # Add custom assets with their paths relative to the static folder
  custom_css = ["css/custom.css"]
  custom_js  = ["highlight/highlight.pack.js"]

  # Choose your social networks
  email = "kearneymw@missouri.edu"
  github = "mkearney"
  twitter = "kearneymw"
  linkedin = "mikewk"
  facebook = "mike.wayne.kearney"

  # Google Webmaster
  # https://www.google.com/webmasters/
  googleSiteVerification = "XjRg6K6oRqzExBrXKJh8Z2BrPJsc9WCVNOEWvhN68oY"

