---
site: blogdown:::blogdown_site
---

### Position

I'm an assistant professor at the University of Missouri where I hold a joint
appointment in Journalism Studies with the School of Journalism and in Data
Science and Analytics with the Informatics Institute. I teach courses in mass
media, political communication, quantitative research methods, and data science.

### Research

My research uses computational social scientific methods to track the
dissemination of information and better understand media selection behaviors
in digital media environments. Broadly, I'm interested in selective exposure,
new media, data journalism, and data science.

Recently, my research has focused on partisan selective exposure in new media
environments. In my dissertation, for example, I studied user networks on
Twitter during the 2016 general election. While I found clear evidence of
network polarization among partisan users, I also found that proximity to the
highly-contentious 2016 election had **NO** effect on non-partisan users,
suggesting that the real gap in today's political landscape may not be between
Republicans and Democrats but between partisans and non-partisans.

### Links

My updated CV can be downloaded
[here](https://dl.dropboxusercontent.com/u/94363099/cv/cv.pdf). Find
me on [Twitter](https://twitter.com/kearneymw), [Google
Scholar](https://scholar.google.com/citations?user=j3EZl3MAAAAJ),
[Github](https://github.com/mkearney), and [Research
Gate](https://www.researchgate.net/profile/Michael_Kearney11). Also
check out my R package, `rtweet`, on the [Comprehensive R Archive
Network
(CRAN)](https://cran.r-project.org/web/packages/rtweet/index.html). For
instructions and access to the development version, check out the
[Github version](https://github.com/mkearney/rtweet) as well!
