---
title: "Tweets about Mueller Investigation"
author: "mwk"
date: "2017-11-02"
slug: r
categories: ["R"]
tags: ["cran", "rstudio", "rstats"]
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(collapse = TRUE)
```

Here's code I used to collect a bunch of data recently.

```{r, eval=FALSE}
## load rtweet
library(rtweet)

## read in where left off
rt <- readRDS("~/Dropbox/pgmm-all2.rds")

## search for 3 million tweets mentioning any of these keywords
rt_ <- search_tweets(
  "papadopolous OR gates OR mueller OR manafort",
  n = 18000L * 10L,
  retryonratelimit = TRUE,
  max_id = max_id(rt)
)

lib(warcraft)

## merge data
rt <- do_call_rbind(list(rt, rt_))

## view time series
ts_plot(rt, "5 mins", trim = 1L) + theme_mwk()

## view date range
range(rt$created_at)

## save
saveRDS(rt, "~/Dropbox/pgmm-all2.rds")

## user defined function to create grouping var with multiple levels
mkp <- function(m, x) {
  kp <- grepl(m, x$text, ignore.case = TRUE)
  usr <- users_data(x)
  usr <- usr[usr$user_id %in% x$user_id[kp], ]
  x <- x[kp, ]
  x$regmatch <- m
  attr(x, "users") <- usr
  x
}

## apply grouping fun to data rt
rtm <- lapply(
  c("mueller", "gates", "papadopoulos", "manafort"),
  mkp, rt
)

## handy new rtweet function for binding a list of tweets/users data
rtm <- do_call_rbind(rtm)

## group using regmatch variable and convert into time series like data
rts <- rtm %>%
  group_by(regmatch) %>%
  ts_data("5 mins", trim = 1L)

## load ggplot2 package
library(ggplot2)

## create ggplot
rts %>%
  mutate(
    regmatch = factor(regmatch, labels = c("Gates", "Manafort", "Mueller", "Papadopolous"))) %>%
  ggplot(aes(x = time, y = n, colour = regmatch)) +
  geom_line() +
  tfse::theme_mwk() +
  labs(
    x = NULL, y = NULL,
    title = "Twitter statuses about recent charges in Mueller's Russia investigation",
    subtitle = "Search terms–Gates, Manafort, Mueller, Papadopolous–aggregated in 5-minute intervals",
    caption = "\nSource: Data (N = 3,149,735) collected from Twitter's search API via rtweet"
  ) +
  theme(
    legend.position = "bottom",
    legend.text = element_text(size = rel(.75)),
    plot.caption = element_text(colour = "gray30", size = rel(.65))
  ) +
  guides(colour = guide_legend(override.aes = list(size = 0.725))) +
  ggsave("~/Desktop/mueller.png", width = 10, height = 7, unit = "in")
```
