---
title: Calling out R-bloggers in my R-bloggers post
author: kearneymw
date: '2018-09-27'
slug: calling-out-r-bloggers-in-my-r-bloggers-post
categories:
  - rstats
tags:
  - r-bloggers
  - data-scribers
  - blogdown
  - rstats
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE, 
  comment = "#>", 
  collapse = TRUE,
  fig.show = "hide"
)
library(tidyverse)
```

Allow me to preface this post by saying I'm a big fan of 
[R-bloggers](https://r-bloggers.com), a content aggregating site focused on 
blog posts about R. It serves a useful purpose,<sup>1</sup> and it appears to have 
considerable reach.<sup>2</sup> And although what follows may seem a 
bit combative, I honestly hope R-bloggers continues to operate
and inspire people to use R for years to come.  

With that said, the goal of this post is to make the case that **R-bloggers 
should be better**. Toward this end, this post proceeds by making the following 
three points:

1. The service provided by R-bloggers can easily be automated
1. R-bloggers profits from content but produces none
1. Its requirements are incommensurate with its contributions

## 1. The service provided by R-bloggers can easily be automated

Without scraping the R-bloggers website or Twitter feed, I was easily able to 
accumulate a large list of R-related blogs and then automate a feed of links to 
blog posts. The task was so easy, I even decided to expand the aim of my 
content aggregating feed to be about data-science more generally–hence, I named 
it `data-scribers`. You can see the site for yourself at 
[data-scribers.mikewk.com](https://data-scribers.mikewk.com).

## 2. R-bloggers profits from content but produces none

The **real** contribution of R-bloggers is not the production of content, but 
the dissemination it. As a result of this contribution, R-bloggers grows its 
reach (fame), functions as a gatekeeper (influence), and generates ad revenue 
(see the plethora of ads populating the site).

I think most would agree the dissemination of content is a valuable contribution,
but, if we're being honest, the heavy lifting–learning, doing, and communicating innovative data science 
things in R–is being done by the bloggers. Anyone with a free afternoon can 
figure out how to string together RSS feeds. But it takes years, decades, or even
lifetimes to equal the amount of training and work done by 750+ bloggers using and 
writing code and data analysis.

## 3. Its requirements are incommensurate with its contributions



## Notes

<sup>1</sup> R-bloggers is a centralized directory of "over 750" R-related blogs

<sup>2</sup> At the time of writing, the site has 50k email subscribers, 60k+ Twitter followers, etc.
